version: '3'

services:
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /u01/mydev/containers-fs-layout/grafana-grafana/data/var/lib/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    restart: unless-stopped
    networks:
      - mon-net

networks:
  mon-net:
    external:
      name: monitoring-net
